// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206170258_createSubunternehmerTable")]
    partial class createSubunternehmerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Baubeginn")
                        .HasColumnType("date")
                        .HasColumnName("Baubeginn");

                    b.Property<string>("Betreff")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Betreff");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<DateTime>("ErstellungsZeit")
                        .HasColumnType("timestamp")
                        .HasColumnName("ErstellungsZeit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<string>("ProjektArt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ProjektArt");

                    b.Property<string>("ProjektBeschreibung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ProjektBeschreibung");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Telefonnummer");

                    b.HasKey("Id");

                    b.ToTable("Kunden", (string)null);
                });

            modelBuilder.Entity("backend.Models.Subunternehmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ansprechpartnername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AnzahlDerMitarbeiter")
                        .HasColumnType("integer");

                    b.Property<string>("Arbeitsregionen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Arbeitsregionen");

                    b.Property<string>("Bankverbindung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Erfarung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ErstellungsZeit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fachgebiet")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Fachgebiet");

                    b.Property<string>("Firmenname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Qualificationen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RechtsformDesUnternehmens")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RechtsformDesUnternehmens");

                    b.Property<string>("Sonstige")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UmsatznsteuerIdentifikationsnummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Verfügbarkeitdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Versicherungsschutz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subunternehmer", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
